version: 0.0

build:
    os: ubuntu-20.04
    tools:
      python: "3.9"
    commands: 
      - mkdir --parents _readthedocs/html/
      - cp --recursive pre_built_html/PDAnalysis* _readthedocs/html/

